### PR TITLE
Expose styling for drawer container

### PR DESCRIPTION
**Pull request by migsc**
People have asked for a way to [customize the drawer's overlay opacity](https://react-navigation.canny.io/feature-requests/p/customize-overlay-opacity-for-drawer) and [color](https://github.com/react-navigation/react-navigation/issues/1068).

To cover all their needs and many others not yet represented, I'd like to propose exposing the container styling of the drawer. This has already been done with the content container styling so I believe this follows the trend.

I've read as much as I could and I couldn't find any arguments as to why this shouldn't be exposed. I'd be interested to hear any feedback and work on adjusting my pull request accordingly.

I'll offer my own usecase here as well. I need to be able to remove the overlay opacity, as well as adjust the position, shadow and border of the drawer container to match a design that I've been provided. Pictured is the result I was able to achieve by exposing the container styles:

screen shot 2018-12-10 at 4 18 56 pm

And I see good reason for this design, since I want to make the list of results under my drawer visible as a user updates their filters inside the drawer. I also want to vertically align the drawer with the button that opens it (not pictured, displayed under the drawer).

Again, I'm open to feedback and any advice on how to proceed. It's my first time submitting a pull request for a major project. Thank you! :)

### CODE REVIEW

**Comment by migsc** [comment]
Done!

**Comment by brentvatne** [comment]
merged in 41c9b34797ab0bd7443ed8a87c0b76ece7e0cfb1

**Comment by brentvatne** [comment]
@migsc - can you add an example of how you would use this in the example project inside of this repo? we're doing a rewrite of DrawerLayout and i want to make sure that we account for this prop, but i'm not familiar with how one might want to use it

**Comment by migsc** [comment]
@brentvatne oh man just saw this. Sorry for the belated response. Do you still need this? I see there's one example that exists already for a styled drawer: https://github.com/react-navigation/drawer/blob/master/example/src/StyledDrawer.js

Would you rather me add the property here with some extra styling? Or create a new example to demonstrate it on its own?

**Comment by brentvatne** [comment]
no worries! was just curious to see how `drawerContainerStyle` was used and have it in an example

**Pull request closed without merging**
