### PR TITLE
support RTL

### PR DESCRIPTION
**Pull request by mhdnet**

### CODE REVIEW

**Comment by dream46453** [comment]
same issue, in rtl mode when drawerPosition is right, container and edge sections are reversed, i mean container section is on the left and edge section is on the right!!! i think when DrawerPosition is on the right, drawer itself get reversed the container and edge and then when the app is on rtl mode container and edge get reversed again! now we should have access to drawerStyle to manualy set flexDirection to "row-reversed", but how can we do it?!

**Comment by dream46453** [comment]
i'm using react navigation totally not just react-navigation-drawer and though couldn't find any drawerLayout to fix the problem locally!!!
 and why no author answers me?!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by mhdnet** [comment]
@dream46453 I'm sorry for the late response
Is this what you're looking for ?
https://github.com/react-navigation/react-navigation-drawer/pull/35/commits/d5c056e906e6ad92bc7718bdfc20595ab1fd03f1

**Comment by brentvatne** [comment]
thanks, I tested this and it resolves the issue reported in https://github.com/react-navigation/react-navigation/issues/5279, much appreciated @mhdnet!

**Comment by brentvatne** [comment]
this is released in react-navigation@3.0.2

**Pull request merged**
