### PR TITLE
Use react-native-gesture-handler/DrawerLayout

### PR DESCRIPTION
**Pull request by brettdh**
Migration of react-navigation/react-navigation#3751.

### CODE REVIEW

**Comment by brettdh** [comment]
@brentvatne I take it CircleCI isn't set up for this yet?

**Comment by brettdh** [comment]
I should note: I didn't migrate the double-close bug fix from the other branch, as I seem to recall seeing other commits to the DrawerNavigator that might have fixed that issue (and I found myself resolving conflicts with those changes frequently). Without it, this patch is very small indeed. 🙂

**Comment by brentvatne** [comment]
@brettdh - correct, I should circle up.

looking good! I need to work out a good strategy for continuing to support the old drawer in this repo at least for the lifetime of react-navigation 2.x and working on this new version at the same time. perhaps I'll create a new branch for this, `next` and merge it in and we can release pre-release versions from there. what do you think?

**Comment by brettdh** [comment]
Sure, makes sense to me.

**Pull request merged**
